<?php

namespace App\Models;

use App\Http\Resources\v1\ApplicantResource;
use App\Scopes\ApplicantScope;
use App\Traits\Offerable;


class Applicant extends User
{
    use Offerable;

    public $transformer = ApplicantResource::class;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ApplicantScope());
    }

    public function vacancies()
    {
        return $this->morphMany(Vacancy::class, 'author');
    }

    public function path()
    {
        return route('applicants.show', $this->id);
    }
}
